### ISSUE TITLE
Reading from subject or result of Datastream.tee() appears to fail silently beyond 32nd item

### ISSUE THREAD

**Issue by alexdunncs** [signicode/scramjet-core#15]
**Basics**
Affects master and teed streams when tee() is called on the master.

**Describe the bug**
The process silently halts, ostensibly when attempting to read the 33rd item from either stream.

**To Reproduce** (self-contained except node/scramjet)
```javascript
const scramjet = require("scramjet");

async function test()  {
    try {

        const minimaltestArr = [{x: 1}, {x: 2}, {x: 3}, {x: 4}, {x: 5}]; // Succeeds
        let thirtyTwoElements = Array.from(Array(32).keys()); //Succeeds
        let thirtyThreeElements = Array.from(Array(33).keys()); //Silently fails/exits, ostensibly after 32nd element (index 31)
        let fiftyElements = Array.from(Array(50).keys()); //Also fails after 32nd element


        const masterStream = scramjet.DataStream.from(fiftyElements);
        const teedStream = masterStream.tee((stream) => stream);

        let masterCount = 0;
        let teedCount = 0;

        ////Uncomment one of the following three blocks to test a scenario

        // Exits after hitting 32 elements from each
        const results = await Promise.all([
            masterStream.each((chunk => {console.log(`p ${masterCount}`);masterCount++;})).toArray(),
            teedStream.each((chunk => {console.log(`c ${teedCount}`);teedCount++;})).toArray()
        ])

        // // Exits after hitting 32 elements of masterStream
        // const masterResults = await masterStream.each((chunk => {console.log(`M ${masterCount}`);masterCount++;})).toArray();
        // const teedResults = await teedStream.each((chunk => {console.log(`T ${teedCount}`);teedCount++;})).toArray();

        // // Exits after hitting 32 elements of teedStream
        // const teedResults = await teedStream.each((chunk => {console.log(`T ${teedCount}`);teedCount++;})).toArray();
        // const masterResults = await masterStream.each((chunk => {console.log(`M ${masterCount}`);masterCount++;})).toArray();

        console.log("Done!");
        const breakpoint = ''; 
    } catch (e) {
    console.log(e);
    const breakpoint = ''
    }   
}

test();

```

**Expected behavior**
results should be an array with two elements, each consisting of an array of fifty integers (when using fiftyElements)

**Test case**
See code, above

**System:**
 - OS: Ubuntu 19.10
 - Node version: v10.15.2
 - Scramjet Version: 4.28.5

**Comment by alexdunncs** [comment]
Per a colleague, extending the array length in test/v1/data-stream.js test_tee to 33 elements causes that test to fail.

**Comment by alexdunncs** [comment]
Failing test example at https://github.com/AJExtravaganza/scramjet-core/commit/9ea161a729b2e143ebd27f4d5fc7fb6d62393e3d

**Comment by MichalCz** [comment]
Yeah, well - that's more like a documentation issue...

See this doc [dataStream.tee](https://scramjet.org/docs/data-stream#module_scramjet.DataStream+tee) is says that the `The duplicate stream will be passed as first argument.`. So in your case the code may look like this:

```javascript
stream.tee(teedStream => teedStream.map(doSoemthing))
```

The idea behind tee is to be able to get a separate path of processing while keeping it in a chain (so it returns the original stream).

What you are trying to achieve (i.e. using the stream with a consume function) could be done by simply taking the stream and piping it to two new streams (that's what tee does underneath), so in your case:

```javascript
        const masterStream = scramjet.DataStream.from(fiftyElements);
        const teedStream = masterStream.pipe(new scramjet.DataStream());
```

I'll write some better documentation around that... I could add a new method for this - but since `tee` was around since **v1.x** I can't change how that works - so a new method name would be needed - `dataStream.copy` maybe? What do you think?

**Comment by alexdunncs** [comment]
Ah, understood - sorry for the misstep.

I think copy makes sense, for such a function.

I do think that more-comprehensive documentation (perhaps through commented usage examples?) would add a lot of value for newcomers to the package, I went through a lot of trial-and-error trying to work out what some of the methods did. I'd be happy contribute to that, with the caveats that 

 - I'm new to Node and Node streams, so perhaps this isn't a concern for your library
 - I'd only be able to contribute examples for methods I confidently understand (see previous)

Either way, I think the package is great and really appreciate the work you've done - thank you!

**Comment by alexdunncs** [comment]
Following up on this, I'm still unclear on why (if this is just a doco issue) extending the unit test from 4 elements to 33 elements causes failure, per https://github.com/signicode/scramjet-core/issues/15#issuecomment-615546322

**Comment by MichalCz** [comment]
Hey @AJExtravaganza 

So the misunderstanding here is that you assumed that tee returns the inner stream, but instead what it does it just executes the callback function passed as the argument with a new instance of the same stream as an argument.

As to the test, I'll get back to you regarding this, meaning, that there might be a separate issue there also.

**Comment by MichalCz** [comment]
Alex, seems you're right: the test as I written it is wrong too... Tee returns the original stream regardless what you pass - that in turn is piped to two `DataStream`s in the example and since those are not read it pauses as soon as the buffer exhausts (32 items by default).

I'll fix the example and add the new `copy` method shortly.

**Comment by alexdunncs** [comment]
Ah, gotcha.  Thanks for the follow-up :)
